version: '3.2'

services:
  # stemmarest:
  #   image: unilenlac/stemmarest
  #   ports:
  #     - 8080:8080

  # stemmaweb:
  #   image: unilenlac/stemmaweb
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - stemmarest

  enlacpipeline:
    image: unilenlac/pipeline
    depends_on:
      - stemmarest
    volumes:
      - type: bind
        source: .
        target: /home
